name: Generate POT

on:
  push:
    tags:
      - "**"
    branches:
      - main

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress POT Generator
      uses: afragen/action-wp-pot-generator@main
      with:
        save_path: './languages'
        item_slug: '${{ github.event.repository.name }}'
        domain: '${{ github.event.repository.name }}'
        package_name: '${{ github.event.repository.name }}'
        headers: '{"Report-Msgid-Bugs-To":"https://github.com/${{ github.event.repository.full_name }}/${{ github.event.repository.name }}/issues"}'
        exclude: '{"./build"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
